version: '3'

services:
  todotests:
    image: todotests
    depends_on:
      - todofront
      - todoback
    restart: always
    environment:
      FRONT_HOST: todofront
      FRONT_PORT: 3000
  todofront:
    image: todofrontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      REACT_APP_API_HOST: todoback
      REACT_APP_API_PORT: 3001
  todoback: 
    image: todobackend
    restart: always
    ports:
      - 3001:3001
